package com.example.model

enum class JarvisState(val label: String, val subtitle: String) {
    IDLE("SYSTEM READY", "AWAITING INPUT"),
    LISTENING("LISTENING...", "RECEIVING AUDIO INPUT"),
    THINKING("PROCESSING...", "ANALYZING COMMAND"),
    SPEAKING("RESPONDING...", "TRANSMITTING SYNTHESIZED SPEECH"),
    EXECUTING("EXECUTING...", "RUNNING ANDROID SYSTEM PROTOCOL"),
    ERROR("ACTION FAILED", "SYSTEM ENCOUNTERED AN EXCEPTION")
}
