package com.example.ai

import android.util.Log
import com.example.ai.gemini.GeminiClient
import com.example.ai.gemini.GeminiContent
import com.example.ai.gemini.GeminiGenerationConfig
import com.example.ai.gemini.GeminiPart
import com.example.ai.gemini.GeminiRequest
import com.example.database.entity.MessageEntity
import com.example.tools.ToolDefinition
import org.json.JSONObject

class GeminiAiProvider : AiProvider {
    override val providerId: String = "gemini"
    override val displayName: String = "Google Gemini AI"

    override suspend fun generateResponse(
        messages: List<MessageEntity>,
        systemPrompt: String,
        tools: List<ToolDefinition>,
        apiKey: String,
        modelName: String
    ): AiResponse {
        if (apiKey.isBlank() || apiKey == "MY_GEMINI_API_KEY") {
            return AiResponse(
                text = "Gemini API key is not configured.",
                isError = true,
                rawError = "MISSING_API_KEY"
            )
        }

        try {
            // Build conversation turns
            val contents = mutableListOf<GeminiContent>()

            // Take last 8 turns for context efficiency
            val contextTurns = messages.takeLast(8)
            for (msg in contextTurns) {
                val role = when (msg.role.uppercase()) {
                    "USER" -> "user"
                    else -> "model"
                }
                val contentText = if (msg.role.uppercase() == "TOOL") {
                    "Tool '${msg.toolName}' result: ${msg.toolResult ?: msg.content}"
                } else {
                    msg.content
                }
                contents.add(
                    GeminiContent(
                        role = role,
                        parts = listOf(GeminiPart(text = contentText))
                    )
                )
            }

            if (contents.isEmpty()) {
                contents.add(GeminiContent(role = "user", parts = listOf(GeminiPart(text = "Status report."))))
            }

            val systemInstruction = GeminiContent(
                parts = listOf(GeminiPart(text = systemPrompt))
            )

            val request = GeminiRequest(
                contents = contents,
                systemInstruction = systemInstruction,
                generationConfig = GeminiGenerationConfig(
                    temperature = 0.3f,
                    maxOutputTokens = 800
                )
            )

            val resolvedModel = if (modelName.isNotBlank()) modelName else "gemini-3.5-flash"
            val response = GeminiClient.apiService.generateContent(
                model = resolvedModel,
                apiKey = apiKey,
                request = request
            )

            val candidate = response.candidates?.firstOrNull()
            val textOutput = candidate?.content?.parts?.firstOrNull()?.text?.trim()

            if (textOutput.isNullOrEmpty()) {
                val err = response.error?.message ?: "No response generated by model"
                return AiResponse(
                    text = "No response from AI model.",
                    isError = true,
                    rawError = err
                )
            }

            // Check if response contains a JSON tool call
            val toolCall = parseToolCall(textOutput)
            return if (toolCall != null) {
                AiResponse(
                    text = "Initiating ${toolCall.name} protocol...",
                    toolCall = toolCall
                )
            } else {
                AiResponse(text = textOutput)
            }

        } catch (e: Exception) {
            Log.e(TAG, "Gemini API execution error", e)
            return AiResponse(
                text = "AI communication error: ${e.localizedMessage ?: "Unknown error"}",
                isError = true,
                rawError = e.message
            )
        }
    }

    private fun parseToolCall(raw: String): AiToolCall? {
        val trimmed = raw.trim()
        val jsonStart = trimmed.indexOf('{')
        val jsonEnd = trimmed.lastIndexOf('}')
        if (jsonStart == -1 || jsonEnd == -1 || jsonEnd <= jsonStart) return null

        val jsonSubstring = trimmed.substring(jsonStart, jsonEnd + 1)
        return try {
            val obj = JSONObject(jsonSubstring)
            val toolName = obj.optString("tool").ifEmpty { obj.optString("name") }
            if (toolName.isNotEmpty()) {
                val argsObj = obj.optJSONObject("arguments") ?: obj.optJSONObject("args")
                val argsMap = mutableMapOf<String, Any?>()
                if (argsObj != null) {
                    val keys = argsObj.keys()
                    while (keys.hasNext()) {
                        val key = keys.next()
                        argsMap[key] = argsObj.get(key)
                    }
                }
                AiToolCall(toolName, argsMap)
            } else {
                null
            }
        } catch (e: Exception) {
            null
        }
    }

    companion object {
        private const val TAG = "GeminiAiProvider"
    }
}
